  ll = LinkedList()
  print("Insert to the linked list")
  ll.insert(2)
  ll.display()
  print("Insert to the linked list")
  ll.insert(52)
  ll.display()
  print("Insert to the linked list")
  ll.insert(12)
  ll.display()
  print("Insert to the linked list")
  ll.insert(18)
  ll.display()
  print("Size of the linked list")
  ll.size()
  print("Search the linked list")
  ll.search(2)
  print("Delete from the linked list")
  ll.delete(52)
  ll.display()
